# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
machine:
    environment:
      PATH: "${PATH}:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin"
jobs:
  build:
    docker:
      - image: cypress/base:10
        environment:
            ## this enables colors in the output
            TERM: xterm
    steps:
      - checkout
      - run: yarn config set workspaces-experimental true
      - run: yarn
      - run: yarn run bootstrap
      - run: yarn run build
      - run:
          name: "Link aws-amplify"
          command: |
            cd packages/aws-amplify
            yarn link
      - run:
          name: "Link aws-amplify-react"
          command: |
            cd packages/aws-amplify-react
            yarn link
      - run:
          name: "Install awsmobile cli"
          command: |
            echo 'export PATH=$(yarn global bin):$PATH' >> $BASH_ENV
            source $BASH_ENV
            yarn global add awsmobile-cli
      - run: 
          name: "Clone auth test package and awsmobile init"
          command: |
            echo "git-codecommit.us-east-1.amazonaws.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCdut7aOM5Zh16OJ+GOP75O7x5oyHKAiA1ieuySetj/hAq4VrAuZV5R2TypZJcKBaripOtTc/Sr0FOU4YvxUla40PPH8N1lbDp6Pnc4BexKsrt2kz++TqIKx5FHmUQV3mit16kxRwHey3dv030+qXBDo3WPQjm2+JLoq0XcadpnCAMCd3ChaBnDRM+51GZbuEFilpZsxUchUzl0gseC+shYOBd7TqxTlIhj/56d/YF1kq7RMZYrwBnyYdVhpLeUJCeYjyx/O6FPSezNTLiinz5jjioWZATgn+G8feL/hIsk8g+7JoIcb2muUlymdxs+8l2lS+8MXqT0q9ohT+Knhb2j" >> ~/.ssh/known_hosts
            git clone ssh://APKAJKAFJK3EYMRBMGEQ@git-codecommit.us-east-1.amazonaws.com/v1/repos/aws-amplify-cypress-auth
            cd aws-amplify-cypress-auth
            yarn
            awsmobile configure aws $IAM_ACCESS_KEY $IAM_SECRET_KEY us-east-1
            awsmobile init --yes 9a71703c-4ae7-49ea-b904-1da5b987937b
      - run:
          command: |
            cd aws-amplify-cypress-auth
            yarn link aws-amplify
            yarn link aws-amplify-react
      - run:
          command: |
            cd aws-amplify-cypress-auth
            yarn start
          background: true
      - run:
          command: |
            yarn cypress --scope aws-amplify-react
      - run: yarn run test --scope aws-amplify
      - run: yarn run test --scope aws-amplify-react
      - run: yarn run coverage
      
      # - run:
      #     name: "Publish to Amplify Package"
      #     command: |
      #       if [ -z "$CIRCLE_PULL_REQUEST" ]; then
      #         echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      #         git config --global user.email $GITHUB_EMAIL
      #         git config --global user.name $GITHUB_USER
      #         yarn run publish:$CIRCLE_BRANCH
      #       else
      #         echo "Skipping deploy."
      #       fi
